### ISSUE TITLE
W jaki sposób generowany jest plik OSM?

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap-polska/CRFOP#1]
Czy jest to robione jakimś skryptem? Jeśli tak - jest może możliwość by go wrzucić do repozytorium?

**Comment by wzbartczak** [comment]
Dane shp wstępnie obrobione w Qgis (tagowanie OpenRefine), potem JOSM - wtedy do OSM. Skrypt przerasta moje możliwości. Dodatkowo jeszcze każde kolejne województwo jest trudniej by nie powielać danych już wprowadzonych.

**Comment by matkoniecz** [comment]
Czyli w QGIS jest przerabiany ręcznie?

**Comment by wzbartczak** [comment]
Tak. Oddzielnie dla każdego województwa.

**Comment by matkoniecz** [comment]
A jest szansa na opisanie co należy zrobić krok po kroku?

Może część jest łatwa do zautomatyzowania, a mógłbym na pewno Małopolskę przerobić.

**Comment by wzbartczak** [comment]
Postaram się.  Chcesz na wiki? Jak u Ciebie z Qgis?

**Comment by matkoniecz** [comment]
Może być na Wiki. Z QGIS nam małe doświadczenie, ale używałem i chętnie dowiem się o nim więcej.

**Comment by matkoniecz** [comment]
Widzę że na https://wiki.openstreetmap.org/wiki/Integracja_danych_CRFOP#Przygotowanie_danych sporo się pojawiło.

Nie wiem czy skończone, ale jedno mi na pewno brakuje - w jaki sposób z tych danych generujemy plik .osm? Ręcznie?

**Comment by wzbartczak** [comment]
No więc jest tak, trochę na okrągło.  Dane csv są po to by móc nimi łatwo manipulować. Do tego dobry jest excel, ale najlepszy jest OpenRefine (soft opensource do manipulacji danymi - java) częściowo pozwala nawet zautomatyzować proces. Jak już dane mam podzielone (na poszczególne wartości "natural" - dla tych plików z wczoraj jeszcze tego nie zrobiłem.) o otagowane, wracaja do Qgisa. Tutaj jeszcze weryfikuję na szybko dublety z OSM (bufor do obiektów już istniejących oraz zaznacz przez lokalizacje), i już w shp, dane lecą do JOSM. Josm generuje plik OSM. Pewnie jest jakiś lepszy sposób na to, ale tak mi jest wygodnie. 
Do piątku nic już nie ruszę za bardzo, więc pliki _all.csv dla poszczególnych województw powinny cię pojawić w weekend. jak będe miał je wszytkie, zrobię podział na tagi, zrobię shp - podmienię pliki Point - w podwieszę osm, bez filtrowania duplikatów.
Na tym etapie postaram się wygenerować dane z kategorii pozostałe, które trzeba będzie ręcznie wklepać.
