### ISSUE TITLE
lubuskie w małopolskim

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap-polska/CRFOP#4]
https://github.com/openstreetmap-polska/CRFOP/tree/master/malopolskie/shp ma pliki z nazwą lubuskie - albo trafiły w złe miejsce albo nazwy są złe

**Comment by wzbartczak** [comment]
Dzieki zaraz posprawdzam

**Comment by wzbartczak** [comment]
Oki wkradł się błąd. Dziś naprawie.
